deploy:
  provider: heroku
  api_key:
    secure: jQp21enjfA1V4/nNjtt/2Oc3ZFUMnDxB51rArsI0euMSfPAw4zDKnru0PVyk7MvrOCWrNPPw5oZowdV6qKBAvLuATHbuuRMUZyuTkgG5lt+Qy1qz16UOXQtEFvGeuFJMYVVK9rgi0t5Ne3gowCpgKydYVq1+C6vYOW4D7IPi7Ywf8tzgDOIF/scDhjfqTX3O2sovqw78IF9t4lN4TQFhzL1m6oawmC0SuDj9rIEsNPhk+nEDiUyVQX1qflOzC923r4Ny64/SeabigHjN7gP5k6flm8ISkxQeFhTW5QtqsNjy6mlQvqYGi0klfyfK1AgFuaYqp1X0ih0H9Ft8WszH4gtFYI6dKcPiTR5H/SeFTXPM9qgdRYB43wfjSp1ypih3mv2yimVzMZQ5eD22OywGPEGBmuMP3EDh06/H+yTRxO34AGTWnA8W4Bz/QWb125LglEuG6Bj2oN8ki1g4rdRvoy9skPcSHEVdVm2saxIvra1BWf9L+FTWmpQ/eWKQp1K6Sbg9or9yFydB4WCfIJyGGejkC3vXxpphZ5M3X6FB0spaNNdFk/4QYchBPEaeW42teUx+IJuc0qzxZRIuwnIDot+zzL6KeZFgqd8odi+uS0wcB61JxyTWnftZ227DhZ5eLq6A1v2iX+dBhIbZ2bWP8xuYPbXb5ZXLt2HWhwsob+0=
  app: Blog-API-Challange
  on:
    repo: GuljanKG/Blog-API-Challange
